### ISSUE TITLE
Switch to Webpack

### ISSUE THREAD

**Issue by jmeas** [babel/generator-babel-boilerplate#230]
Esperanto and Rollup rely on Acorn, which doesn't seem like a tool that is likely to support as many features as Babel (for instance, stage 0 proposals). Perhaps it's time to look into other module loaders (webpack?) to see if any exist that offer full Babel support.

Ref #218

===

Todo:

- [x] build for browser tests with src maps
- [x] ensure browser tests can be written in ES2015+
- [x] build for distribution with src maps
- [x] Update README with future ES support

A few things left to do for browser tests:

- [x] ~~Prevent double linting~~ nvm this wasn't happening. I was misinterpreting the command line output

**Comment by Kflash** [comment]
@jmeas You have plans for adding webpack? Any links to a site using this boilerplate with webpack?

**Comment by jmeas** [comment]
> You have plans for adding webpack?

Maybe, not sure yet. Gotta do some research when I've got time.

> Any links to a site using this boilerplate with webpack?

Nope.

**Comment by jmeas** [comment]
I'll likely switch to webpack if it:

1. has no acorn dep
2. can replace esperanto *and* browserify

**Comment by jmeas** [comment]
Some history:

- I thought I considered webpack once before, but I can't find any history of that
- [I used 6to5 originally](https://github.com/babel/generator-babel-boilerplate/blob/5a8f147c70ec19d2040f469eee68012723cd099a/gulpfile.js#L27) with [that old wrapper file](https://github.com/babel/generator-babel-boilerplate/blob/24faa04ef94c03345ea71f81988b35c90c7a20dd/src/wrapper.js)
- Shortly after, [I added Browserify](https://github.com/babel/generator-babel-boilerplate/commit/5a0c8a5db669149385e566359bae4ec7d900d54a) to enable testing in the browser
- @thejameskyle recommended I could get rid of the wrapper file by either extending Babel. I opted for Esperanto instead. Conversation here: https://github.com/babel/generator-babel-boilerplate/issues/30

**Comment by jmeas** [comment]
The last remaining issue is replacing Browserify with Webpack. I was having one issue where it was difficult to get Webpack to take multiple entry points and concatenate them. I added `gulp-concat` to manage that for me, but it's not working when `watch` is set to `true` for webpack (that option must make it a never-ending stream, so it never gets past it).

**Comment by jmeas** [comment]
I might be able to achieve this with dynamic requiring. In pseudocode:

```js
// test/setup/browser.js

// Get an array of test file names
var tests = resolveAllTestFiles();
tests.forEach(filename => require(filename));
```

No idea if this is possible...but it probably is, because Webpack is insane.

**Comment by jmeas** [comment]
For live reloading, `webpack-stream` offers a third argument that is a callback! Yes!

**Comment by jmeas** [comment]
I fixed the problem with `gulp-concat` after `webpack-stream` in https://github.com/shama/webpack-stream/pull/80, but it doesn't help. When webpack's watch is run, it doesn't cause `concat` to be run again, so it's kinda worthless.

Is there a way to get webpack working with `gulp.watch` in a nice way? What I did with browserify was use watchify, which had the capabilities to do `n=>1` building. I opened an issue on Webpack's issue tracker (https://github.com/webpack/webpack/issues/1506) to see if this was possible using Webpack.

If none of this ends up working, and I must stick with Browserify, then the next steps would be figuring out to get browserify to support module proxying.

**Comment by jmeas** [comment]
Another route to try with Webpack is the developer server. This would basically move me 100% off of Gulp for the browser tests, but maybe that's okay? One concern is how to make listing work as the user changes files.

**Comment by jmeas** [comment]
Nice. The last missing piece I needed was `n=>1` bundling, which is provided by the `LimitChunkCountPlugin` (explained to me in this issue https://github.com/webpack/webpack/issues/1506 )

Pretty excited!

**Comment by jmeas** [comment]
Done!

**Comment by alex88** [comment]
@jmeas I've just installed the latest version but I still get the `[DEPRECATION NOTICE] Esperanto is no longer under active development. To convert an ES6 module to another format, consider using Babel (https://babeljs.io)` error, what should I do?

**Comment by alex88** [comment]
Nvm, my fault, just seen it's in the v6 branch!

**Comment by jmeas** [comment]
Hey @alex88 , this is a technicality, but that's not an error, just a warning. Esperanto is great! I'm still using it on a few projects I haven't migrated over yet. Sorry for the slow release of v6; I'm balancing life and work 🙂. Feel free to help out if you've got time!
